import type { Lead } from '@/types';

export const SAMPLE_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    role: 'bride',
    weddingDate: '2024-09-14',
    packageId: 'signature',
    dogName: 'Winston',
    dogBreed: 'Golden Retriever',
    dogSize: 'large',
    status: 'confirmed',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Emily Chen',
    email: 'emily.chen@email.com',
    role: 'bride',
    weddingDate: '2024-10-05',
    packageId: 'essential',
    dogName: 'Bella',
    dogBreed: 'French Bulldog',
    dogSize: 'small',
    status: 'pending',
    createdAt: '2024-01-18T14:30:00Z',
  },
  {
    id: '3',
    name: 'Marcus Thompson',
    email: 'marcus.t@email.com',
    role: 'groom',
    weddingDate: '2024-11-22',
    packageId: 'luxury',
    dogName: 'Duke',
    dogBreed: 'Border Collie',
    dogSize: 'medium',
    status: 'lead',
    createdAt: '2024-01-20T09:15:00Z',
  },
];
