import type { Lead, Dog } from '@/types';

export const SAMPLE_DOGS: Dog[] = [
  {
    id: 'dog-1',
    name: 'Winston',
    breed: 'Golden Retriever',
    size: 'large',
    temperament: 'calm',
    specialNeeds: '',
  },
  {
    id: 'dog-2',
    name: 'Luna',
    breed: 'French Bulldog',
    size: 'small',
    temperament: 'energetic',
    specialNeeds: 'Needs frequent water breaks',
  },
];

export const SAMPLE_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Amanda & Trevor H.',
    email: 'amanda@example.com',
    phone: '555-0101',
    role: 'client',
    weddingDate: '2024-09-14',
    venue: 'Napa Valley Estate',
    packageId: 'signature',
    dogId: 'dog-1',
    status: 'confirmed',
    notes: 'Wants tuxedo to match groomsmen charcoal suits.',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'lead-2',
    name: 'Chloe & Marcus T.',
    email: 'chloe@example.com',
    phone: '555-0102',
    role: 'client',
    weddingDate: '2024-10-05',
    venue: 'Chicago Botanic Garden',
    packageId: 'luxury',
    dogId: 'dog-2',
    status: 'in-progress',
    notes: 'Gown should match blush bridesmaid dresses.',
    createdAt: '2024-02-03T14:30:00Z',
  },
  {
    id: 'lead-3',
    name: 'Priya & James S.',
    email: 'priya@example.com',
    phone: '555-0103',
    role: 'planner',
    weddingDate: '2024-11-22',
    venue: 'The Plaza Hotel, NYC',
    packageId: 'essential',
    dogId: '',
    status: 'inquiry',
    notes: 'Wedding planner coordinating on behalf of couple.',
    createdAt: '2024-03-10T09:15:00Z',
  },
];
