import type { Lead } from '@/types';

export const SAMPLE_LEADS: Lead[] = [
  {
    id: 'lead_001',
    name: 'Amanda Harrison',
    email: 'amanda@example.com',
    role: 'bride',
    dogName: 'Winston',
    dogBreed: 'Golden Retriever',
    dogAge: '3',
    eventDate: '2024-09-14',
    goalStatement: 'I want Winston to walk down the aisle with me.',
    packageId: 'signature',
    status: 'confirmed',
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'lead_002',
    name: 'Chloe Thompson',
    email: 'chloe@example.com',
    role: 'bride',
    dogName: 'Luna',
    dogBreed: 'Poodle',
    dogAge: '2',
    eventDate: '2024-10-05',
    goalStatement: 'Luna should match the bridesmaids.',
    packageId: 'elite',
    status: 'inquiry',
    createdAt: '2024-06-15T14:30:00Z',
  },
  {
    id: 'lead_003',
    name: 'James Murphy',
    email: 'james@example.com',
    role: 'groom',
    dogName: 'Bear',
    dogBreed: 'Labrador',
    dogAge: '5',
    eventDate: '2024-11-20',
    goalStatement: 'Bear is our ring bearer.',
    packageId: 'essential',
    status: 'inquiry',
    createdAt: '2024-07-01T09:00:00Z',
  },
];
